name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install deps and build
        run: pnpm install && pnpm vupdate && pnpm prebuild && pnpm build &&  pnpm tauri build

      # Make empty folders for plugins and themes
      - name: Create empty folders for plugins and themes
        run: mkdir src-tauri/target/release/plugins && mkdir src-tauri/target/release/themes

      - name: Compress build
        uses: edgarrc/action-7z@v1
        with:
            args: 7z a -tzip Dorion.zip src-tauri/target/release/dorion.exe src-tauri/target/release/config.json src-tauri/target/release/plugins/ src-tauri/target/release/themes/ src-tauri/target/release/injection src-tauri/target/release/html/ src-tauri/target/release/icons/

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Dorion_win64_portable.zip
          path: Dorion.zip

      - name: Upload MSI
        uses: actions/upload-artifact@v3
        with:
          name: Dorion_win64.msi
          path: src-tauri/target/release/bundle/msi/*.msi

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install libraries
        run: sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install deps and build
        run: pnpm install && pnpm vupdate && pnpm prebuild && pnpm build &&  pnpm tauri build

      - name: Create empty folders for plugins and themes
        run: mkdir src-tauri/target/release/plugins && mkdir src-tauri/target/release/themes

      # Zip
      - name: Compress build
        run: cd src-tauri/target/release && touch config.json && tar -czvf dorion.tar.gz dorion config.json ./plugins ./themes ./injection ./html ./icons

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Dorion_amd64_portable.tar.gz
          path: dorion.tar.gz

      # Upload deb
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: Dorion_amd64.deb
          path: src-tauri/target/release/bundle/deb/*.deb

      # Upload AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Dorion_Amd64.AppImage
          path: src-tauri/target/release/bundle/appimage/*.AppImage
  
  build-macos:
    runs-on: macos-12
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Add arch target
      - name: Add arch64 target
        run: rustup target add aarch64-apple-darwin

      - name: Install deps and build
        run: pnpm install && pnpm vupdate && pnpm prebuild && pnpm build &&  pnpm tauri build --target universal-apple-darwin

      # Zip artifact folder
      - name: Compress build
        run: zip -r Dorion.zip src-tauri/target/release/

      - name: Upload .app
        uses: actions/upload-artifact@v3
        with:
          name: Dorion.app
          path: src-tauri/target/release/universal-apple-darwin/bundle/macos/*.app

      # Upload dmg
      - name: Upload dmg
        uses: actions/upload-artifact@v3
        with:
          path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
