name: Check frontend

on:
  push:
    paths-ignore:
      - '**.lock'
      - '**.rs'
      - '**.toml'
  pull_request:
    paths-ignore:
      - '**.lock'
      - '**.rs'
      - '**.toml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tsc-eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install modules
        run: yarn
      - name: Run tsc
        run: pnpm tsc --noEmit
      - name: Run ESLint
        run: pnpm eslint ./src
